import { expect, test } from 'vitest'
import { Recipe } from '../../model/Recipe'

test('has the correct properties and types', () => {
    const recipe: Recipe = {
        RecipeId: '1',
        Name: 'Test Recipe',
        AuthorId: 'author123',
        AuthorName: 'Test Author',
        CookTime: '30 minutes',
        PrepTime: '15 minutes',
        TotalTime: '45 minutes',
        DatePublished: '2023-12-31',
        Description: 'This is a test recipe.',
        RecipeCategory: 'Test Category',
        Keywords: ['test', 'recipe'],
        RecipeIngredientParts: ['1 cup flour', '2 eggs'],
        AggregatedRating: '4.5',
        Calories: '250',
        FatContent: '10g',
        SaturatedFatContent: '3g',
        CholesterolContent: '50mg',
        SodiumContent: '300mg',
        CarbohydrateContent: '30g',
        FiberContent: '5g',
        SugarContent: '10g',
        ProteinContent: '15g',
        RecipeServings: '4',
        RecipeYield: '1 cake',
    }

    expect(recipe).toEqual({
        RecipeId: expect.any(String),
        Name: expect.any(String),
        AuthorId: expect.any(String),
        AuthorName: expect.any(String),
        CookTime: expect.any(String),
        PrepTime: expect.any(String),
        TotalTime: expect.any(String),
        DatePublished: expect.any(String),
        Description: expect.any(String),
        RecipeCategory: expect.any(String),
        Keywords: expect.arrayContaining([expect.any(String)]),
        RecipeIngredientParts: expect.arrayContaining([expect.any(String)]),
        AggregatedRating: expect.any(String),
        Calories: expect.any(String),
        FatContent: expect.any(String),
        SaturatedFatContent: expect.any(String),
        CholesterolContent: expect.any(String),
        SodiumContent: expect.any(String),
        CarbohydrateContent: expect.any(String),
        FiberContent: expect.any(String),
        SugarContent: expect.any(String),
        ProteinContent: expect.any(String),
        RecipeServings: expect.any(String),
        RecipeYield: expect.any(String),
    })
})
